### ISSUE TITLE
Allow running script before/after the rsync

### ISSUE THREAD

**Issue by diggy128** [Manko10/rs-backup-suite#10]
It would be nice to be able to run scripts before/after the actual sync much like rsnapshot's cmd_preexec and cmd_postexec.
This could be of use for creating database dumps that are later synced to the backup server.

**Comment by Manko10** [comment]
You can do that by simply wrapping rs-backup-run into another shell script.
But I'll add that to the feature wishlist since it's really easy to implement.

**Comment by diggy128** [comment]
Yes, that was my first thought but then I would lose the wonderful idea you implemented by wrapping the backup as a service.
It could definitely be done a million ways, but I would be nice to be a feature upstream.

**Comment by Manko10** [comment]
Together with lots of other improvements (most client and server-side logging) I also implemented three options now:

--pre-hook: command to be run before starting the backup
--post-hook: command to be run after backup has successfully finished
--forced-post-hook: command to be run after the backup, even if it finished with errors

For further information have a look at the help text of rs-backup-run.
