### ISSUE TITLE
sh scripts return errors with dash

### ISSUE THREAD

**Issue by lukeolson** [Manko10/rs-backup-suite#7]
On systems where `sh` is not `bash` (e.g. Ubuntu: https://wiki.ubuntu.com/DashAsBinSh) there are issues with the scripts:
`sudo ./install server`
needs to be run as
`sudo bash ./install server`
since errors are return like:
`install.sh: 29: install.sh: [[: not found`

I think that `#!/bin/sh` needs to be changed throughout (to `#!/bin/bash`)

**Comment by Manko10** [comment]
This long-term issue has been resolved now. All scripts are using Bash instead of a POSIX shell now.
