### ISSUE TITLE
location of rsnapshot.global.conf

### ISSUE THREAD

**Issue by lsandig** [Manko10/rs-backup-suite#9]
What is the location of `rsnapshot.global.conf` supposed to be?

The install.sh script puts it into `"$BKP_DIR"/etc/rsnapshot.global.conf` (line 172), but the file `rsnapshot.conf.template` expects it to be at `${BKP_ROOT}/etc/rs-backup/rsnapshot.global.conf`.

This is inconsistent. Please fix either path.

**Comment by Manko10** [comment]
Hi,

I don't know why it was etc/rsnapshot. It certainly wasn't like that before. I fixed it. Thanks for your report.
